server:
  port: 9002
  
spring:
  zipkin:
    base-url: http://localhost:9411/
  application:
    name: team-service
    
  kafka:
    consumer:
      group-id: teamGroup
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      bootstrap-servers: localhost:9092
      properties:
        "[spring.json.type.mapping]": team:com.example.team.entity.Team
        
        
eureka:
  instance:
    hostname: localhost
        
        