server:
  port: 8999
  
eureka:
  instance:
    hostname: localhost
    
spring:
  application:
    name: api-gateway
   
  cloud:
    gateway:
      routes:
      - id: project-service
        uri: lb://project-service
        predicates:
          - Path=/employee/**
      
