server:
  port: 9003
  
spring:
  zipkin:
    base-url: http://localhost:9411/
  application:
    name: project-service
    
  kafka:
    consumer:
      group-id: projectGroup
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      bootstrap-servers: localhost:9092
      properties:
        "[spring.json.type.mapping]": project:com.example.team.entity.Project
        
        
eureka:
  instance:
    hostname: localhost
        
        